name: python simple build
on :[push]
jobs:
  build:

    runs-on : ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up python

        uses: actions/setup-python@v5
        with:
          python-versoin: '3.x'

      - name: run the python code
        run : pyton simple.py
