name: "Terraform"
on:
  push:
    branches:
      - main
jobs:
  terraform:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan

      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve -input=false 
        env:
          access_key=${{secrets.access_key}}
          secret_key=${{secrets.secret_key}}
          
