name: "Terraform"
on:
  push:
    branches:
      - main
jobs:
  terraform:

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan

      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve -input=false